name: Pack for Distribution
on: push

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

    - name: Pack source into a single file
      run: npm run pack

    - name: Commit distribution build
      uses: endbug/add-and-commit@v4
      with:
        add: "dist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


